### ISSUE TITLE
IOS: G+ Application available but browser opened.

### ISSUE THREAD

**Issue by Moussawi7** [EddyVerbruggen/cordova-plugin-googleplus#181]
Hi,
After updating my :
-OSX to 10.11.3
-XCode to 7.2.1
-cordova to 6.0
-IOS to 9.2.1
the plugin stopped opening G+ application, and the authorization is made on the browser.
Note that :
```javascript
  window.plugins.googleplus.isAvailable(function(avail) {alert(avail)});
```
always alert ***true***.
Any action needed?!
Thank you.

**Comment by MathieuDuboy** [comment]
i have exactly the same problem as you.
avail is always true (even when the Native google+ App is deleted) and safari is always called.

Have you find the problem ?
Thanks

**Comment by MathieuDuboy** [comment]
So, since this update 
4.0.3: On iOS isAvailable always returns try since that should be fine with the new Google SignIn framework. Re-added imageUrl to the result of SignIn on iOS.

But why on IOS 9.X.X safari is called instead of Native app ?
Is there a way to be rejected by Apple if Safari is called instead of native app ?
Thank you.

**Comment by Moussawi7** [comment]
@MathieuDuboy .
In fact, i didn't find a solution for this issue so i used an older version.
And be worry Apple will reject the app if the authentication are made in a browser instead of application, and for this reason the author create the method ***isAvailable**.

**Comment by shinyMetilda** [comment]
Actually the authentication is made via Webview in google SDK. Google has provided its own custom SDK due to iPhone rejection issue and it no longer opens the g+ app. This is fine. If you are getting redirection issue when using this plugin (i.e redirction to google.com), try this fork https://github.com/shinyMetilda/cordova-plugin-googleplus

**Comment by sammuggPS** [comment]
Hey @Moussawi7 and @MathieuDuboy,

I merged a significant PR the other day that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out. To install it, use the second (GitHub URL) method found in the [README](https://github.com/EddyVerbruggen/cordova-plugin-googleplus#4-installation-phonegap-cli--cordova-cli).

Version 4.0.6 of this app and on have been using Google Sign-In for iOS. The latest, [pre-release] v4.0.9, uses Google Sign-In for both platforms. The isAvailable function is no longer required to use Google Auth and will likely be removed in a future release.

Let me know if you have any questions!

Happy Coding,
~Sam
P.S. If your issue gets resolved, please close it!
