### ISSUE TITLE
Googleplus open in safari and not returing any info.

### ISSUE THREAD

**Issue by shivam5x** [EddyVerbruggen/cordova-plugin-googleplus#189]
Hi,
  I am using googleplus plugin but it is not doing as we want and most important it doesn't return any value and stay in safari. As your plugin set for G+ availability it is return true but not in app , going to safari.

Please let me know the solution if some found.

Thanks
Shivam

**Comment by danicastanos** [comment]
+1

**Comment by shinyMetilda** [comment]
Try this fork of the plugin https://github.com/shinyMetilda/cordova-plugin-googleplus

**Comment by sammuggPS** [comment]
Hey @danicastanos, @marcin-piela, and @shivam5x, thanks for pointing this out.

@shinyMetilda is correct: the isAvailable function isn't needed any more. His PR was merged just the other day and worked like a charm!

I just merged a significant update yesterday that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out. Let me know if y'all have any questions!

Happy Coding,
~Sam

P.S. Close this issue if you're good to go!

**Comment by bau720123** [comment]
hi @sammuggPS 
could I ask，which one is the official version (by git) ? (I know the npm is old version for now)
yours or @EddyVerbruggen ?

because of yours and @EddyVerbruggen almost have the same code，in addition to this file have a lot of different
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/src/android/GooglePlus.java
https://github.com/PointSource/cordova-plugin-googleplusupdate/blob/master/src/android/GooglePlus.java
