### ISSUE TITLE
No Cancel or Back button in IOS 8 / Fine in IOS 9

### ISSUE THREAD

**Issue by MathieuDuboy** [EddyVerbruggen/cordova-plugin-googleplus#194]
Hi, Thanks for this great plugin.
I have a little issue that annoys me a lot !
When i'm logged out (or logged) from my google Account, in IOS 8 there is no way to go back to the app.
I have to kill the app to restart it.
![img_1893](https://cloud.githubusercontent.com/assets/11943636/13898460/b5c8bc0a-edd1-11e5-98e0-888256d5621d.PNG)

In Ios 9, a webview is open in the app and everything is fine. I can Quit, Go back, Cancel 
How can i fix this please ?
I don't want to hide my Login with Google button if the user has IOS8.
thanks for your time.

**Comment by sammuggPS** [comment]
Hey @MathieuDuboy, thanks for pointing this out.

This issue lies with Google and Apple. With iOS 9, Apple introduced a new type of WebView called the [SafariViewController](https://developer.apple.com/videos/play/wwdc2015/504/). It does not exist on iOS 8 and back, which is why you've run into this problem. Your best bet would be to explore Apple's [WebView documentation](https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/). As the speaker said in the SVC video I linked to, it's up to the developer to configure the WKWebView.

Sidenote: I know this can be frustrating, but keep at it.

I just merged a significant update yesterday that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out. Let me know if you have any questions!

Happy Coding,
~Sam
