### ISSUE TITLE
 GLSUser : java.io.IOException: Invalid device key response.

### ISSUE THREAD

**Issue by carlosdubus** [EddyVerbruggen/cordova-plugin-googleplus#201]
Anyone getting the following on android?

`GLSUser : java.io.IOException: Invalid device key response.`

I'm using the emulator. The google dialog appears, I try to log in, then I get an alert saying Error: 12051. I looked at the logcat and right after I try to log in I get the following exception:

```
GLSUser : [AppCertManager] IOException while requesting key: 
GLSUser : java.io.IOException: Invalid device key response.
GLSUser : 	at com.google.android.gms.auth.be.appcert.a.a(SourceFile:268)
GLSUser : 	at com.google.android.gms.auth.be.appcert.a.a(SourceFile:132)
GLSUser : 	at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
GLSUser : 	at com.google.android.gms.auth.b.b.a(SourceFile:62)
GLSUser : 	at com.google.android.gms.auth.b.a.a(SourceFile:120)
GLSUser : 	at com.google.android.gms.auth.b.a.a(SourceFile:61)
GLSUser : 	at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
GLSUser : 	at com.google.android.gms.gcm.au.run(SourceFile:140)

```

Thanks!

**Comment by sammuggPS** [comment]
@carlosdubus,

First things first, are you using the latest version of the plugin? I merged a PR the other day that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes.

Second, are you using an emulator image that includes the Google APIs? From the error, it looks like you are, but I want to make sure.

Third, also on the note of Google APIs, do you have the latest APIs installed for your version of android? Do you have the latest android-support, android build-tools, and play services installed?

Fourth, is your project properly set up on the Developer's Console? Are you using the correct SHA1 in the Android permissions?

Just want to make sure that your platform is up to date, because the error looks like it's internal to the account usage API. All this plugin does is start that process.

Happy Coding,
~Sam
P.S. If your issue gets resolved, please close it!

**Comment by carlosdubus** [comment]
Hi Sam. I appreciate your detailed response. The issue was the SHA1. I was creating a new keystore instead of using the debug.keystore one. So I used ~/.android/debug.keystore file to get the SHA1 and I added the following build.json file to my cordova project:

```
{
    "android": {
        "debug": {
            "keystore": "~/.android/debug.keystore",
            "storePassword": "android",
            "alias": "androiddebugkey",
            "password" : "android",
            "keystoreType": ""
        }
    }
}
```

That did the trick... Hopefully this helps someone else.

**Comment by sammuggPS** [comment]
@carlosdubus Awesome! Glad I could be of help.
