### ISSUE TITLE
Subsequent calls are blocking

### ISSUE THREAD

**Issue by trancee** [EddyVerbruggen/cordova-plugin-googleplus#31]
When using the calls from the plugin with Cordova 4.0.0, the first call succeeds as expected, but any subsequent calls are blocking (never returning).

LogCat is showing the following entries:
12-30 09:11:48.925: I/System.out(22771): {"iOSApiKey":"XXX.apps.googleusercontent.com"}

Whenever I call the plugin function, e.g. trySilentLogin, it always only works the first time. Then it just is not returning anymore with every call.

What am I doing wrong?

**Comment by EddyVerbruggen** [comment]
I don't think the problem was with blocking the response, rather the `onConnected` event in Android was never fired again as the app was already connected to Google Play Services. This meant the JS callback was never invoked as you observed.

I just changed the `connect` function to `reconnect` which effectively forces `onConnected` to be filed every time you call `login` or `trySilentLogin` which means your callbacks are now always invoked.

Wished I found this a few months ago, but still..
