### ISSUE TITLE
USER CANCELLED

### ISSUE THREAD

**Issue by Moussawi7** [EddyVerbruggen/cordova-plugin-googleplus#5]
I installed the plugin on a clean cordova 3.6 project, but when i try to login an error occurred saying "USER CANCELLED".

**Comment by tkuben** [comment]
I am also getting the same error. I've tried to reinstall the plugin and rebuild but no luck. When I look at logcat I am seeing the following

W/PluginManager(17288): THREAD WARNING: exec() call to GooglePlus.login blocked the main thread for 46ms. Plugin should use CordovaInterface.getThreadPool().
D/cr_Ime  (17288): [ImeAdapter.java:213] updateKeyboardVisibility: type [0], flags [0], show [true]
D/cr_Ime  (17288): [AdapterInputConnection.java:178] updateState [] [0 0] [-1 -1] [true]
D/ActivityManager( 3602): retrieveServiceLocked(): component = null; callingUser = 0; userId(target) = 0
D/ActivityManager( 3602): retrieveServiceLocked(): component = null; callingUser = 0; userId(target) = 0
D/ActivityManager( 3602): retrieveServiceLocked(): component = null; callingUser = 0; userId(target) = 0
E/Parcel  ( 3602): Class not found when unmarshalling: com.google.android.gms.common.api.Scope
E/Parcel  ( 3602): java.lang.ClassNotFoundException: com.google.android.gms.common.api.Scope
E/Parcel  ( 3602):      at java.lang.Class.classForName(Native Method)
E/Parcel  ( 3602):      at java.lang.Class.forName(Class.java:309)
E/Parcel  ( 3602):      at java.lang.Class.forName(Class.java:273)
E/Parcel  ( 3602):      at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
E/Parcel  ( 3602):      at android.os.Parcel.readParcelable(Parcel.java:2245)
E/Parcel  ( 3602):      at android.os.Parcel.readParcelableArray(Parcel.java:2338)
E/Parcel  ( 3602):      at android.os.Parcel.readValue(Parcel.java:2206)
E/Parcel  ( 3602):      at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
E/Parcel  ( 3602):      at android.os.BaseBundle.unparcel(BaseBundle.java:221)
E/Parcel  ( 3602):      at android.os.BaseBundle.getString(BaseBundle.java:918)
E/Parcel  ( 3602):      at android.content.Intent.getStringExtra(Intent.java:5767)
E/Parcel  ( 3602):      at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2365)
E/Parcel  ( 3602):      at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1848)
E/Parcel  ( 3602):      at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6308)
E/Parcel  ( 3602):      at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:257)
E/Parcel  ( 3602):      at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6086)
E/Parcel  ( 3602):      at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:262)
E/Parcel  ( 3602):      at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3821)
E/Parcel  ( 3602):      at android.os.Binder.execTransact(Binder.java:461)
E/Parcel  ( 3602): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Scope" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
E/Parcel  ( 3602):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  ( 3602):      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/Parcel  ( 3602):      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/Parcel  ( 3602):      ... 19 more
E/Parcel  ( 3602):      Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.api.Scope
E/Parcel  ( 3602):              at java.lang.Class.classForName(Native Method)
E/Parcel  ( 3602):              at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/Parcel  ( 3602):              at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/Parcel  ( 3602):              at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/Parcel  ( 3602):              ... 20 more
E/Parcel  ( 3602):      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
V/ApplicationPolicy( 3602): isApplicationStateBlocked userId 0 pkgname com.google.android.gms
D/CustomFrequencyManagerService( 3602): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1800000  uid : 1000  pid : 3602  pkgName : ACTIVITY_RESUME_BOOSTER@6
W/ActivityManager( 3602): mDVFSHelper.acquire()
V/WindowManager( 3602): addAppToken: AppWindowToken{82bf819 token=Token{1aa07b60 ActivityRecord{37697363 u0 com.google.android.gms/.signin.activity.SignInActivity t10687}}} to stack=1 task=10687 at 1
I/ActivityManager( 3602): Skip updateThumbnail for r=ActivityRecord{3b8383e6 u0 com.phonegap.riipe/.MainActivity t10687}


any thoughts?
